# AC Unity two-monitor workaround for the custom DXVK build.
# Try 1 first. If the game still opens on the 1080p monitor, try 0.
dxgi.outputIndex = 1

dxgi.hideIntegratedGraphics = True
dxvk.allowFse = False
dxgi.syncInterval = 0
